---
name: ci
permissions:
  contents: read

on:
  # for feature branches and releases
  push:

concurrency:
  group: ${{ (github.ref != 'refs/heads/master') && format('{0}-{1}', github.ref, github.workflow) || github.run_id }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

jobs:
  ci:
    name: ci
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1

      - run: |
          IMAGE_NAME=riak_exporter:latest
          CONTAINER_NAME=riak_exporter
          PPORT=8097

          docker buildx build . --load --tag "${IMAGE_NAME}"
          docker run --detach --rm --name "${CONTAINER_NAME}" -p "${PPORT}":8097 "${IMAGE_NAME}"

          sleep 5

          METRICS=$(curl localhost:"${PPORT}")
          EXPECTED="<a href=\"/metrics\">/metrics</a>"
          if [[ "${METRICS}" != "${EXPECTED}" ]]; then
            echo "curl returned ${METRICS}, but we expected ${EXPECTED}!"
            exit 1
          else
            docker stop "${CONTAINER_NAME}"
            echo "All good!"
          fi


  release:
    if: github.ref == 'refs/heads/master' && startsWith(github.event.head_commit.message, 'no-release:') == false
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
      with:
        fetch-depth: 0
        token: ${{secrets.GITHUB_TOKEN}}

    - name: Bump version and push tag
      id: tag-version
      uses: mathieudutour/github-tag-action@a22cf08638b34d5badda920f9daf6e72c477b07b # v6.2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        dry_run: true
        release_branches: master

    - name: Create a GitHub release
      run: |
        if ! command -v gh >/dev/null 2>&1; then
          curl -sS https://webi.sh/gh | sh
        fi
        gh release create ${{ steps.tag-version.outputs.new_tag }} --generate-notes --latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
